language: php
php:
 - 5.3

env:
 - DB=MYSQL CORE_RELEASE=3.1
 - DB=MYSQL CORE_RELEASE=master
 - DB=PGSQL CORE_RELEASE=master

matrix:
  include:
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=master COVERAGE=1

before_script:
 - pear -q install --onlyreqdeps pear/PHP_CodeSniffer
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

#script:
# - phpunit cloudassets/tests/

script:
 - "if [ \"$COVERAGE\" = \"\" ]; then phpunit -c cloudassets/phpunit.xml.dist; fi"
 - "if [ \"$COVERAGE\" = \"1\" ]; then phpunit -c cloudassets/phpunit.xml.dist --coverage-clover cloudassets/coverage.xml; fi"

after_script:
 - if [ "$COVERAGE" = "1" ]; then
 - cd cloudassets
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload -v --format=php-clover coverage.xml
 - fi
